[[Qt6Quick3D]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1353b2ad2eea690b6af6afac6f390a1cdb8bb170"
libc = "musl"
os = "linux"

    [[Qt6Quick3D.download]]
    sha256 = "348a735c068d4e25a982cc2b66cc08c9f9da2ee786035fad2cac09e2c8188ea5"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Quick3D_jll.jl/releases/download/Qt6Quick3D-v6.10.2+0/Qt6Quick3D.v6.10.2.x86_64-linux-musl-cxx11.tar.gz"
