name = "Qt6Quick3D_jll"
uuid = "6dc365b9-5e99-58d6-8812-efce7277b6ef"
version = "6.10.2+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Qt6Declarative_jll = "629bc702-f1f5-5709-abd5-49b8460ea067"
Qt6ShaderTools_jll = "ce943373-25bb-56aa-8eca-768745ed7b5a"
assimp_jll = "54ae6823-98c6-5a7c-8365-5a43b909f91f"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Qt6Base_jll = "c0090381-4147-56d7-9ebc-da0b1113ec56"
Qt6QuickTimeline_jll = "aaa24d55-1a42-52ef-a112-65a2da50b610"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
Qt6Declarative_jll = "=6.10.2"
Qt6ShaderTools_jll = "=6.10.2"
assimp_jll = "6.0.4"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
Qt6Base_jll = "=6.10.2"
Qt6QuickTimeline_jll = "=6.10.2"
